---
title: "Research Proposal"
author: "Benedikt Abendroth and Katrin Heger"
date: "21. Oktober 2015"
output: pdf_document
bibliography:
- bibliography.bib
---

# Introduction And Research Question
After the end of the Cold War there was optimism that the number of conflicts would decrease. But this hope was dashed with the emergence of numerous intrastate conflicts in Europe, Africa, and Asia. Although the incidences of conflict have declined over the last decade, the world seems far from being in peace with conflicts raging in Syria, Ukraine, Yemen, South Sudan and the DR Congo. Conflicts on average last longer, are more violent and prone to reoccur. Not only are these internal violent armed conflicts associated with high costs in terms of human lives, they also plummet states into economic depression and spill over to neighboring countries, thereby negatively affecting the economy and stability of entire regions. The international community finds itself in the position of deciding whether it should merely stand idly by or actively intervene into conflicts, may it be for humanitarian or strategic reasons. A growing reluctance to engage militarily in states at war is partly due to a decreasing willingness to risk one’s own soldiers’ lives in conflicts abroad and partly due to the failure rate of previous military interventions.  In this context, delivering weapons to conflict zones has become a convenient solution for many Western states that constitutes a middle ground between being a passive bystander and sending troops. In Syria, the US provided weapons to the rebels fighting the autocratic Assad regime and in Ukraine, the pro-government forces have received arms in order to fight the separatist movement. This idea of helping warring parties help themselves is not new. During the Cold War, the US and the USSR frequently lent “support of an indirect nature” (Henderson 2013, 643) to government and opposition groups in so-called proxy wars. The delivery of arms to war zones like Nicaragua or Laos was conducted covertly, with the intervenors being aware of both the illegality and the questionable morality of such weapons transfers.  While there are all sorts of legal and moral deliberations dominating the debate on interventions in policy circles as well as in academia, the question of whether this form of intervention actually works is addressed less systematically. This paper tries to fill this gap by investigating the relationship between the delivery of weapons as one form of international intervention and its success in ending civil war. 

# Literature Review
In the literature, several options for outside actors to intervene in conflicts have been explored theoretically. According to Snyder and Jervis (1999), conflict situations can be analyzed in the framework of a security dilemma. A “security dilemma is a situation in which each party’s efforts to increase its own security reduce the security altogether” (Snyder/Jervis 1999, 15). The idea of a security dilemma stems from the philosophy of Thomas Hobbes, who laid out the state of nature as a state of war.  Hobbes deduces his state of nature from conditions of human nature. He assumes that people are similar in their mental and physical capacities and thus no one is able to dominate the other. Humans are further inherently egoistic and rational in their striving to achieve their own goals. Under conditions of anarchy and resource scarcity, these attributes of human nature lead to a violent struggle for survival. People feel threaten by others and engage in pre-emptive attacks as a means of anticipatory defense, which ultimately results in a spiral of violence, a ‘war of all against all’. In the state of nature, people lead a life that is “solitary, poor, nasty, brutish, and short” (Hobbes 1651, Chapter 13). In order to escape this situation, they voluntarily agree to appoint a sovereign government – the state – by entering in a social contract. In exchange for giving up (some of) their freedom, they are guaranteed peace and security (ibid).
While the security dilemma is primarily applied to describe the relationship between states in international relations theory, some scholars have adopted it as a tool to analyze civil wars (Visser/Duyvesteyn 2014). According to this narrative, civil wars very much resemble the Hobbesian state of nature, in which conditions of anarchy due to lacking state capacities and competition over territory and power might make attack the best form of defense when one feels threatened. 
Within the framework of the security dilemma, ending a war means breaking off the dilemma structure. One resolution to the civil war security dilemma is one party achieving military victory and as a result taking over the rule. Although a winner dominating the losers of the war is not equal to Hobbes’ idea of a sovereign to whom the citizens of a state voluntarily render parts of their sovereignty, the underlying mechanisms are the same. The winner will disarm his opponents and unite all the power, thereby creating stability (Duffy Toft 2010). Empirical evidence proves that civil wars ending in the military defeat of one party are less likely to relapse into violence than conflicts ending with negotiated settlements. This finding has prompted some scholars to argue for a laissez-faire approach towards civil conflicts, suggesting that it might be best to “give war a chance” (Duffy Toft 2010, 7) and let the parties fight until a clear winner emerges. 
Applying this logic to foreign interventions, Snyder and Jervis (1999) and Regan (1996) suggest for third-party interveners to change the dilemma structure either by increasing the costs for the parties to fight and reducing the costs of peace or by putting in place a hegemonic power that imposes peace on the warring parties. While changing the incentive structure can be achieved by negotiating peace agreements or by implementing monitoring mechanisms like peacekeeping operations, dominating power can be established by implementing outside rule or by strengthening one side in the conflict in order to make it the dominant group (Snyder/Jervis 1999, 27). 
In an early attempt to quantify the relationship between foreign intervention and civil wars, Regan (1996) investigated the conditions for successful third-party intervention into intrastate wars. He found that it is the type of the intervention strategy rather than the nature of the conflict that determines the success of an intervention. Distinguishing between two intervention strategies, military and economic intervention, Regan established that a mix of the two strategies rather than either type alone would be more effective. However, he found that in general, conflicts experiencing external interventions are less likely to terminate than those without. These findings were confirmed in Regan’s subsequent research that modeled the success of an intervention as a function of (1) the strategic environment in which the  conflict  is  being  waged;  (2)  the  existence  of  a  humanitarian  crisis  associated  with  the conflict; (3) the number of fatalities; and (4) the intensity of the conflict (Regan 2002). 
The early 2000s saw a broad range of similar quantitative research, establishing links between intervention and the duration of civil war as well as the number of casualties. Lacina (2006) testifies that conflicts with interventions result in significantly higher numbers of fatalities and Cunningham (2010) evokes that the involvement of third parties significantly prolongs civil wars. Elbadawi & Sambanis (2000) modeled in how far supporting the rebels or supporting the government makes a difference for the duration of conflict. Taking into account the strategic considerations rebels and governments make when faced with a potential intervention, they find that the net effect of intervention on the duration of conflict is negative. For example, Elbadawi & Sambanis discovered that interventions backing rebels against autocratic regimes prolong conflicts because they strengthen rebellions that could have been defeated easily otherwise. 
Most of this research, however, failed to disentangle various forms of interventions by lumping together military intervention on the one and economic intervention on the other hand. This generic approach to intervention opens up a gap for us to investigate the specific effects of arms supply to one side of the conflict. 

# Data Sources
Using datasets from the University of Uppsala Conflict Database Program (UCDP), we seek to examine the relationship between delivering lethal military equipment, weapons, as one form of third-party intervention and their potential to end violent conflicts. 
There are obvious limitations to the data and it might be biased for two reasons: First, data might be incomplete because weapons transfers might happen covertly due to legal issues and strategic reasons. Second, data on lethal aid might bear a selection bias since it is likely that only countries that assumed they would be successful with an intervention decide to intervene and are included in the sample (Regan 1996, 342). 

# Methodology
We base our definition of conflict on the terminology introduced by UCDP together with the Peace Research Institute Oslo (PRIO) (Themnér and Wallensteen 2011; Gleditsch et al. 2002). A ‘major armed conflict’ or ‘war’ is characterized by at least 1,000 battle related, military or civilian, deaths a year, while conflicts with 25 to 999 battle deaths a year are categorized as ‘minor armed conflict’. They further distinguish other forms of violence from conflicts by adding the component of an organized effective violent opposition to the government, thereby excluding genocides and similar forms of violence from their definition of conflict. 

Drawing from Regan (1996), we call our dependent variable success of intervention, which is operationalized as the “cessation of military hostilities for a period lasting at least six months” (Regan 1996, 343). Our independent variable is weapons delivery to one party in the conflict with the aim of enabling it to defeat the other side. 
In order to isolate the effect of arms transfers on the termination of civil wars, we will have to control for conflict dynamics and external factors. Conflict dynamics can be measured in terms of the type of conflict, the military strength of the warring parties, the time period before the intervention, and whether the supported party is the government or the rebel group. External circumstances we might have to control for is other strategies used simultaneously by third parties, such as economic aid or weapons embargoes on the opposing faction. 

# References