---
title: "Third-Party Intervention in Intrastate War"
subtitle: "Do Outcomes Match Intensions?"
author: "K Heger & B Abendroth"
date: "17 December 2015"
output: 
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
  html_document:
    fig_caption: yes
    number_sections: yes
    toc: yes

bibliography: BibliographyFinal.bib
---
\pagebreak

#Introduction 

After the end of the Cold War there was optimism that the number of conflicts would decrease but this hope was dashed with the emergence of numerous intrastate conflicts in Europe, Africa, and Asia. Although the incidences of conflict have declined over the last decade, the world seems far from being in peace with conflicts raging in Syria, Ukraine, Yemen, South Sudan and the DR Congo. Not only are these internal violent armed conflicts associated with high costs in terms of human lives, they also plummet states into economic depression and spill over to neighboring countries, thereby negatively affecting the economy and stability of entire regions. These kinds of conflicts have become increasingly difficult to resolve and the international community finds itself in the position of deciding whether it should merely stand idly by or actively intervene into conflicts, may it be for humanitarian or strategic reasons. 
Existing literature in the field of civil wars has shown that third party intervention can both promote and inhibit the ongoing conflicts. While the presence of impartial third parties as guarantees can act as a de-escalator to conflicts (Walter 2002), direct military support to one conflict side or the other potentially prolongs wars (Regan 2002). However, there are other forms of outside support than troops. A growing reluctance to engage militarily in states at war is partly due to a decreasing willingness to risk one's own soldiers' lives in conflicts abroad and partly due to the failure rate of previous military interventions. In this context, delivering money, weapons, and training to conflict zones has become a convenient solution for many Western states that constitutes a middle ground between being a passive bystander and sending troops. In Syria, the US provided weapons to the rebels fighting the autocratic Assad regime and in Ukraine, the pro-government forces have received arms in order to fight the separatist movement. This idea of helping warring parties help themselves is not new. During the Cold War, the US and the USSR frequently lent "support of an indirect nature" [@henderson2013provision, 643] to government and opposition groups in so-called proxy wars. The delivery of arms to war zones like Nicaragua or Laos was conducted covertly, with the intervenors being aware of both the illegality and the questionable morality of such weapons transfers. 
While there are all sorts of legal and moral deliberations dominating the debate on interventions in policy circles as well as in academia, the question of which form of intervention is successful in what respects is addressed less systematically. This paper tries to contribute to existing research by investigating the relationship between various forms of third-party intervention (military, non-military, troops) into intrastate wars and different conflict outcomes (rebel or government victory, negotiated settlement, low intensity conflict). We find that....

The paper proceeds as follows: In the following part, we review some of the relevant literature on intrastate conflict intervention and termination. Part 3 presents our theoretical model from which we derive four hypotheses about the impact of different types of third party intervention on the outcome of conflict. After establishing our methodology in part 4, we empirically test this model in section 5. Part 6 presents our results and we conclude the paper in section 7. 
	

#Literature Review

In the literature, several options for outside actors to intervene in conflicts have been explored theoretically. In early research, Snyder and Jervis (1999) suggest that conflict situations can be analyzed in the framework of a security dilemma. A "security dilemma is a situation in which each party's efforts to increase its own security reduce the security altogether" [@jervis1999civil, 15]. While the security dilemma is primarily applied to describe the relationship between states in international relations theory, some scholars have adopted it as a tool to analyze civil wars [@visser2014irrelevance]. According to this narrative, civil wars very much resemble the Hobbesian state of nature, in which conditions of anarchy due to lacking state capacities and competition over territory and power might make attack the best form of defense when one feels threatened. 
Within the framework of the security dilemma, ending a war means breaking off the dilemma structure. One resolution to the civil war security dilemma is one party achieving military victory and as a result taking over the rule. The winner will disarm his opponents and unite all the power, thereby creating stability [@toft2010ending]. Empirical evidence proves that civil wars ending in the military defeat of one party are less likely to relapse into violence than conflicts ending with negotiated settlements. This finding has prompted some scholars to argue for a laissez-faire approach towards civil conflicts, suggesting that it might be best to "give war a chance" [@toft2010ending, 7] and let the parties fight until a clear winner emerges. Applying this logic to foreign interventions, Snyder and Jervis (1999) and @regan1996conditions suggest for third-party interveners to change the dilemma structure either by increasing the costs for the parties to fight and reducing the costs of peace or by putting in place a hegemonic power that imposes peace on the warring parties. While changing the incentive structure can be achieved by negotiating peace agreements or by implementing monitoring mechanisms like peacekeeping operations, dominating power can be established by implementing outside rule or by strengthening one side in the conflict in order to make it the dominant group [@jervis1999civil, 27]. 

In an early attempt to quantify the relationship between foreign intervention and civil wars, Regan (1996) investigated the conditions for successful third-party intervention into intrastate wars. He found that it is the type of the intervention strategy rather than the nature of the conflict that determines the success of an intervention. Distinguishing between two intervention strategies, military and economic intervention, Regan established that a mix of the two strategies rather than either type alone would be more effective. However, he found that in general, conflicts experiencing external interventions are less likely to terminate than those without. These findings were confirmed in Regan's subsequent research that modeled the success of an intervention as a function of (1) the strategic environment in which the  conflict  is  being  waged; (2)  the  existence  of  a  humanitarian  crisis  associated  with  the conflict; (3) the number of fatalities; and (4) the intensity of the conflict [@regan2002civil; @regan2002third]. 

The early 2000s saw a broad range of similar quantitative research, establishing links between intervention and the duration of civil war as well as the number of casualties. @lacina2006explaining testifies that conflicts with interventions result in significantly higher numbers of fatalities and @cunningham2010blocking evokes that the involvement of third parties significantly prolongs civil wars. 

Related to that, a further strand of literature emphasizes the goals and the bias of the interveners. Regan (2002) established that a unilateral intervention in general leads to longer wars, while impartial interventions have to potential to shorten conflicts. Contrary to that, Cunningham (2010) shows that engagement by third parties with an unbiased agenda and goals independent of any of the warring sides, prolong civil wars. 

Elbadawi and Sambanis (2000) were amongst the first to distinguish between a third party lending support to the rebels or government. In the logic of the security dilemma, this distinction is void since intervention is merely about balancing out the powers, no matter on which side. @elbadawi2000external modeled in how far supporting the rebels or supporting the government makes a difference for the duration of conflict. Taking into account the strategic considerations rebels and governments make when faced with a potential intervention, they find that the net effect of intervention on the duration of conflict is negative. Elbadawi and Sambanis discovered that interventions backing rebels against autocratic regimes prolong conflicts because they strengthen rebellions that could have been defeated easily otherwise. 

In a very recent article, Sullivan and Karreth (2015) explore this relationship further. Taking rebel and government military strength into account, they argue that the success of third party intervention on either side in the form of troops depends on the relative military capacities of the warring parties. Disaggregating different conflict outcomes (rebel victory, government victory, negotiated settlement, and low intensity conflict), the article concludes that troop 
support to rebels increases the likelihood of rebel victory and reduces the likelihood of low intensity conflicts. Military assistance to the government, on the other hand, influences the outcome of conflict only, when the rebels are sufficiently strong because otherwise, additional military capacities for the government are unlikely to be critical to regime survival. Assistance to a severely threatened government significantly improves the odds of regime survival and reduces the likelihood of rebel victory, while supporting a relatively strong government does not affect the odds of any of the conflict outcomes. 

Instead of differentiating between various conflict outcomes, Sawyer et al. (2015) focus on different types of support such as weapons, money, intelligence, or troops, and argue that they have different effects on the chance of an intrastate conflict ending. Looking at support to the rebel side only, they establish that more fungible resources given to rebels decrease the chances of civil war termination, while other types of support have either no or the opposing effect. Their argument is that the most fungible forms of support to rebels create uncertainty about rebel capability on the state side, which on the one hand inhibits the state's willingness to negotiate settlements and on the other sets incentives for the rebels to continue fighting. 


#Third Party Intervention and Conflict Outcomes

This paper tries to combine this research by examining how different types of interventions in support of either the rebels or the government affect the outcome of a conflict. In this section, we put forward a theoretical framework for our analysis, utilizing a mixture of the asymmetric power and bargaining approach. 

##Asymmetric Power in Civil Wars
We assume that a civil war has the following structure: An intrastate war begins with a rebel group attacking the state. Rebels are generally weaker than the government and engage in unconventional military tactics like terrorism or guerilla warfare. Government, on the other hand, has stronger military capacities and "presents a non-elusive target" [@butler2009asymmetry, 337], as their conventional force makes is difficult for them to hide from the opposition. In a cost benefit logic, rebels try to impose costs on the government by engaging in indirect war fighting strategies and the government, in turn, evaluates when these costs get too high and react to the conflict accordingly [@cunningham2009takes].
First, if the rebels impose costs on the state that are high enough that the state feels threatened, the state fights the rebels back. The success of the government in defeating the rebels depends on the strength of the rebel group. If the group is relatively strong and has sufficient military capabilities, it is easier for the government to target the rebels with conventional military power. If the opposition is weak and a diffuse target, the government is unlikely to be successful in defeating the rebels entirely [@butler2009asymmetry]. 
Second, instead of trying to defeat the opposition, governments can offer a peace settlement, which the rebels can accept or decline. The government seeks settlement with the opposition, if a) the costs of completely defeating the rebels are relatively high and b) it can be assumed that the rebels are unlikely to resume fighting. In order to provoke a government reaction, the rebels thus need to send a strong signal of their capacity since states are only willing to bargain with and make concessions to opposition groups that can cause a certain threshold of damage [@walter2009bargaining]. At the same time, while the incumbent government usually has the better bargaining position due to its relatively stronger military power, there is a high degree of uncertainty about the rebels' capacity to continue fighting [@sawyer2015role]. Under these circumstances, the government has to evaluate whether it is likely that the rebels resume fighting. If it perceives it as probable that the rebels will not keep their part of the agreement, a negotiation offer is unlikely. The rebels accept and maintain peace, when it is their best alternative, considering their own and the governments fighting capacity and their resulting likelihood to either win or enforce further concessions. Rebels can "bluff their way to more concessions" [@sawyer2015role] by pretending to be stronger than they are. This strategy, however, bears the risk of the government continuing to fight and pulling back the peace offer. 

Conflict outcome is thus a function of both government and rebel capacities. A rebel military victory should be rare overall, simply because rebels lack the military capacities to challenge a government. At the same time, a clear defeat of the rebels is difficult to achieve because conventional government forces are less successful in asymmetric warfare. Consequently, state forces prevail in most intrastate conflicts but rebel groups can survive by using asymmetric warfare tactics over an extended period of time. Once the costs inflicted by rebels become too high, the government can extend a bargaining offer, if it expects the rebels to accept it. The opposition accepts the offer and sticks to it, when they believe to have received the best possible offer. 


##Third-party Intervention
These dynamics can change when third parties intervene from the outside and influence the fighting capacities of rebels or the state. We distinguish between three different types of support warring parties can receive - troops, military, and non-military.  
Gent (2008) argues that rebel-biased troop support is more effective than government-biased foreign interventions in producing the intended result of a military victory of the respective side. He appeals to the idea that outside forces only intervene on behalf of the rebels if they conceive the rebels as strong and likely to prevail in first place. Consequently, with rebel support, there is an ex ante bias for a rebel victory because military intervention is more likely in the cases where rebels are much stronger anyway.
At the same time, providing rebels with other forms of military support, such as heavy military equipment, might in fact increase the chances of winning for the government. A higher military sophistication might force the rebels to shift their strategy away from guerilla tactics because they can no longer operate in the hide, which will lead to more exposure and confrontational clashes with the government forces. Assuming that an asymmetry of power prevails even with military support, weak conventional rebel forces might be an easy target for stronger government troops [@sullivan2014conditional]. 
In a similar rationale, providing troops or military equipment to the government does not make a government victory more likely, since conventional force is only effective when it can be directed against a specific, visible target. Asymmetric power distribution in a civil war can render government military force highly ineffectual against weak rebel groups practicing guerilla warfare. Troops and military support from a third party increase the likelihood of government victory only, when rebel troops are sufficiently strong [@butler2009asymmetry]. 
While troops and other forms of military support can only be used in a very specific way within a limited timeframe, more "fungible" [@sawyer2015role], non-military types of support can be utilized in various ways and at various points in time. Money, as the most fungible resource, can be invested into infrastructure, recruitment, training, or arms, it can be saved or spent immediately, and it is thus more difficult for the government to assess changing rebel capacities [@hazen2013rebels]. 
Consequently, when rebels receive non-military outside support, uncertainty on the government side increases and creates credibility and commitment problems that prevent negotiations from taking place. On the one hand, governments might be less willing to settle the conflict because they expect rebels to break the peace agreement. On the other, rebels might not be willing to commit to peace in the first place, because their increased capacities might change their assumptions about their abilities to fight the government in the future [@sawyer2015role].  
Within our theoretical framework, it is unclear how non-military support should differ from development programmes or financial aid. We thus cannot establish a direct link between non-military support to the incumbent and conflict outcomes. However, we should expect to see a similar effect to the provision of troops and military equipment, since financial means allow the government to upgrade their military capacities. Again, the state can only benefit from conventional military power if the opposition constitutes a tangible target.  

Assuming that a third party intervening would want to either bring about a victory of the supported party or promote a negotiated settlement, we can derive a set of hypothesis:

$H_1a: Troops support to rebels will increase the probability of rebel military victory. 
$H_1b: Military support to rebels will increase the probability of government military victory, and decrease the probability of rebel military victory. 
$H_2: Troops and military support to governments will increase the probability of government military victory only when opposition military strength approaches that of the state.
$H_3: Non-military support to rebels decreases the likelihood of a negotiated settlement. 
$H_4: Non-military support to governments will increase the probability of government military victory only when opposition military strength approaches that of the state.
	

#Methodology

This section sets the methodological framework for our analysis. After presenting some definitions, we introduce our data and variables and describe the choice of our research design. 

##Definitions and Level of Analysis
We base our definition of conflict on the terminology introduced by UCDP together with the Peace Research Institute Oslo (PRIO) [@themner2011armed; @gleditsch2002armed]. A 'major armed conflict' or 'war' is characterized by at least 1,000 battle related, military or civilian, deaths a year, while conflicts with 25 to 999 battle deaths a year are categorized as 'minor armed conflict'. They further distinguish other forms of violence from conflicts by adding the component of an organized effective violent opposition to the government, thereby excluding genocides and similar forms of violence from their definition of conflict. 
As is common in recent conflict research, Sullivan and Kenneth take conflict dyads as their level of analysis, modeling civil wars as dyadic struggles between the government and an opposition party instead of focusing on the state-level. Conflict dyads record each violent interaction between an incumbent regime and an opposition and this unit of analysis thus allows us to isolate the effect of weapons deliveries to one side of the dyad and its effect on ending violence. Both NSA data as well as UCDP data are available as conflict dyads, which makes a merging of different datasets easier.

##Data 
We use as a baseline for our analysis a publicly available dataset created by Sullivan and Karreth [@sullivan2014conditional], which  will henceforth be referred to as the CIMI Dataset. Sullivan and Karreth draw from the 3.3 version of the Non-state Actors (NSA) dataset [@cunningham2013non], as well as the University of Uppsala Conflict Data Program's (UCDP) Conflict Termination Dataset [@kreutz2010and] and External Support Dataset [@hogbladh2011external].  For the purpose of testing our hypotheses, we complement the CIMI dataset with additional variables included in the NSA data, which leaves us with 497 conflict dyad spells over a period of time from 1946 to 2010. 

Our dependent variable is conflict outcome, since we are interested in the impact of outside intervention on the termination of conflict. We adopt conflict_outcome from the CIMI Dataset, which disaggregates outcome into four different conflict outcomes coded from the UCDP Conflict Termination Dataset. Accordingly, internal conflicts either fade out into a period of low activity (0), they end with a victory by the rebels (1), they terminate with some form of negotiated settlement (2), or with government victory (3). The most common outcome for a conflict dyad is low activity, defined as a violent conflict with less than 25 deaths per year for at least one year. While 44% of all conflict dyads level off like that, 35% end in a victory of one side. Governments win the conflict in 22% of the cases, rebels prevail in only 13%. 21% of conflicts terminate with a negotiated settlements.  

Our main explanatory variable is the type of support provided to government and rebels by third parties. Drawing from the NSA Dataset, we create two variables for support to the rebels (rtypesupport) and to the government (gtypesupport) and code them as categorical variables. The limited availability of detailed conflict data only allows us to distinguish between three different categories, troops (1), military (2), and non-military support (3), as coded in the NSA Dataset. Although the dataset does not provide us with a more detailed description of what is included in each category [@cunningham2013non], we can nevertheless use the variable as a proxy to test our theoretical model. While the provision of troops is an unambiguous category, military and non-military support are not as clear-cut classifications. However, the variable captures the basic idea of non-military support to rebels creating uncertainty and military support increasing the conventional military capacity of rebels. In 20% of the cases, governments are supported with troops, in 72% they receive some other form of military support. Only in 7% of the cases, third-party governments support the government with non-military means. Similar to support to governments, by far the most common type of support is military support with 70%. Both troops and non-military support are less frequent with 14% and 15%, respectively. 

The second key explanatory factor in our theory is a party's military capacity relative to the opponent's capacity. CIMI operationalizes rebel military capacity as a dichotomous variable with rebels at least as militarily strong as the government coded 1, and rebels weaker as the government in terms of personnel, weapons, and equipment as 0. Since fighting capacity is coded as a relative measure, CIMI introduces the log of GDP per capita as a measure for government strength since rebels could be strong in relation to a weak government and at the same time have very limited actual capacities [@sullivan2014conditional]. Since we hypothesized that the success of intervetion on government side depends on the strength of the rebels (Hypotheses 2 and 4), we code an interaction term between rebel fighting capacity and a pro-government intervention dummy variable. 
We further identify a set of control variables that might influence war outcomes. As is common in civil war research, we control for post-Cold War conflicts by adding a Cold War dummy. Negotiated settlements have become more and military victories less likely after the Cold War due to the increasing willingness of the international community to intervene and mediate conflicts [@fortna2004have; @kreutz2010and; @toft2010ending]. 
It further has been suggested that the duration of the conflict and government success are negatively associated because rebels are more likely to gain strength over the duration of a conflict [@brandt2008and; @karl2004dynamics]. We control for duration by including the natural log of the conflict duration in years. 
Taking into account the motivation of the rebels, we borrow from Sullivan and Karreth a variable indicating whether the war is a secessionist conflict because we expect that secessionist wars affect conflict outcomes differently than wars aiming at regime change [@karl2004dynamics; @regan2002civil]. Similarly, we control for whether the rebel group has a legal political wing that could be integrated into the government [@cunningham2009takes]. 

##Statistical Model
In our research, we seek to examine how different types of external support to both rebels and governments during civil war influence the outcome of conflicts. In line with this encounter, we apply a regression design to assess the relationship between conflict outcome as our dependent variable and the support type as explanatory variables. 
Since our dependent variable is a discrete variable, taking on four different values (0 = low intensity conflict, 1 = victory, 2 = negotiated settlement, 3 = victory), we employ a logistic regression model. We combine these regressions into one model by estimating a multinomial logistic regression with conflict outcome as a dependent variable with four categories. Since the categories are not ordinal, a simple multinomial model is appropriate. 

\begin{equation}\begin{aligned} Pr(Y_{i}=j) = \frac{exp(X_{i}\beta_{j})} {\sum_{j=1}^{J} exp(X_{i}\beta_{j})}\end{aligned}\end{equation}

In our model, j represents each of the four outcomes and i indexes the unit of analysis, being a dyadic episode of intrastate armed conflict. Following Sullivan and Karreth, we omit the most common conflict outcome, low intensity conflict, as the baseline category and calculate estimates for the remaining outcomes government victory, negotiated settlement and rebel victory.The results tell us how different kinds of third-party intervention affect the likelihood of a conflict having a specific outcome vs. the reference (low intensity conflict).


#Results and Discussion
In this section, we present and discuss our statistical findings and the quality of our model. Overall, our hypotheses were supported by the data. However, some limitations in 

##Intervention in SUpport of the Government

Troops and military support to governments will increase the probability of government military victory only when opposition military strength approaches that of the state.

Non-military support to governments will increase the probability of government military victory only when opposition military strength approaches that of the state.

##Intervention in Support of the Opposition

Troops support to rebels will increase the probability of rebel military victory. 

Military support to rebels will increase the probability of government military victory, and decrease the probability of rebel military victory.

Non-military support to rebels decreases the likelihood of a negotiated settlement.

##Control Variables
Similar to Sullivan & Karreth's findings, we see a 
duration of conflict
secessionist
Cold War
legal wing

##Model Quality
Prior to conducting the multinomial regressions, we correlated our independent variables and could exclude multicollinearity issues. We further tested for the validity of the independence of irrelevant alternatives (IIA), an assumption underlying multinomial regression models, with a Hausman test. 

In our 497 observation, we only had 40 complete cases, which left us with very limited data to test our theory. As lies in the nature of conflict data, the availability is very limited. 

#Conclusion
In policy-making, intervention is often depicted as a solution to internal conflicts, while at the same time, academic research has revealed that intervention oftentimes rather prolongs and exacerbates civil wars. In this paper, we set out to contribute to the current civil war research by examining closer the relationship between different forms of third-party intervention into intrastate conflict and conflict outcomes. We derived a theoretical model from the assumption that under the conditions of asymmetric power in civil wars, rebels and government face a bargaining problem. We hypothesized that troops and other forms of military and non-military support provided to the government increase the likelihood for a military victory of the incumbent only, when rebel forces are sufficienlty strong and thus constitute a tangible target. Troop support to rebels, on the other hand, has an unconditional positive effect on the likelihood of rebel victory. Supplying rebels with military equipment should, in fact, decrease the probability of the opposition winning because it makes them more vulnerable to conventional governemnt force. When rebels receive non-military assistant from a third party, negotiated settlements become less likely because more fungible support creates uncertainty about the credible commitment of rebels to peace, which might deter the government from bargaining in first place. 
Our statistical analysis indicated that

Disaggregating the categories of non-military and military support further, could be a fruitful encounter for future research. 

\pagebreak

#References
